export const SET_SUBSCRIPTION_DATA = 'SET_SUBSCRIPTION_DATA';
export const SET_SUBSCRIPTION_STEP = 'SET_SUBSCRIPTION_STEP';
export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_RECENT_SEARCHES = 'UPDATE_RECENT_SEARCHES';