export const SUBSCRIPTION_STEP = {
  FREE_TRIAL: 'FREE_TRIAL',
  NO_ACTIVE_SUBSCRIPTION: 'NO_ACTIVE_SUBSCRIPTION',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE: 'PAYMENT_FAILURE',
  MANUAL_PAYMENT: 'MANUAL_PAYMENT',
  CLOSED: 'CLOSED',
};